version: "2"

services:

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"


  app:
    build: .
    container_name: "app"
    depends_on:
      - "redis"
    ports:
      - "8080:8080"